[package]
name = "hello_world"
version = "0.1.0"
authors = ["Wangweizhen <hawking.rei@gmail.com>"]
edition = "2018"

[dependencies]
spdk-sys = { path = "../../../spdk-sys" }
libc = "0.2.43"
lazy_static = "1.1.0"