[package]
name = "spdk-rs"
version = "0.1.0"
authors = ["Wangweizhen <hawking.rei@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "example/nvme/hello_world",
]
default-members = [
    "example/nvme/hello_world",
]
[dependencies]
